services:
  mockx-oracle:
    build:
      container_name: mockx-oracle
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env
    ports:
      - "6379:6379"
    restart: unless-stopped
