[tool.poetry]
name = "mockx-oracle"
version = "0.1.0"
description = "MockX Oracle - Price feed service for MockExchange"
authors = ["Didac <didac.crst@gmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.12"
ccxt = "^4.2.91"
redis = "^5.0.1"
pydantic = "^2.7.0"
python-dotenv = "^1.0.1"

[tool.poetry.group.dev.dependencies]
pytest = "^8.2"
pytest-cov = "^5.0"
pytest-mock = "^3.14"

[tool.pytest.ini_options]
testpaths = ["tests"]
python_files = ["test_*.py"]
python_classes = ["Test*"]
python_functions = ["test_*"]
addopts = [
    "--strict-markers",
    "--strict-config",
    "--cov=oracle",
    "--cov-report=term-missing",
    "--cov-report=html:htmlcov"
]

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
