services:
  mockx-engine:
    build:
      container_name: mockx-engine
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env
    ports:
      - "8000:8000"
    restart: unless-stopped
