services:
  mockx-periscope:
    build:
      container_name: mockx-periscope
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env
    ports:
      - "8501:8501"
    restart: unless-stopped
