[tool.poetry]
name = "mockexchange-periscope"
version = "0.1.0"
description = "Streamlit dashboard for mockexchange_api (paper-trading PoC)"
authors = ["Didac <didac.crst@gmail.com>"]
readme = "README.md"
packages = [{ include = "app" }]

[tool.poetry.dependencies]
python = "^3.12"
streamlit = "^1.37.0"
streamlit-autorefresh = "^1.0.0"
pandas = "^2.2"
numpy = ">=1.26.0,<2.0.0"
requests = "^2.32"
python-dotenv = "^1.0"
plotly = "^5.22"
pydantic = "^2.7"
streamlit-aggrid = "0.3.*"

[tool.poetry.group.dev.dependencies]
black = "^24.3"
ruff = "^0.4"
pytest = "^8.0"
pytest-cov = "^5.0"
pytest-mock = "^3.14"
httpx = "^0.27"

[tool.pytest.ini_options]
testpaths = ["tests"]
python_files = ["test_*.py"]
python_classes = ["Test*"]
python_functions = ["test_*"]
addopts = [
    "--strict-markers",
    "--strict-config"
]

[tool.ruff]
target-version = "py312"
line-length = 88

[tool.ruff.lint]
select = [
    "E",  # pycodestyle errors
    "W",  # pycodestyle warnings
    "F",  # pyflakes
    "I",  # isort
    "B",  # flake8-bugbear
    "C4", # flake8-comprehensions
    "UP", # pyupgrade
]
ignore = [
    "E501",  # line too long, handled by black
    "B008",  # do not perform function calls in argument defaults
    "C901",  # too complex
    "E731",  # lambda assigned to name (refactor later)
    "UP040", # TypeAlias -> `type` keyword (refactor later)
]

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"