name: Integration Tests

on:
  workflow_dispatch: {}

jobs:
  integration:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Install Poetry
        uses: snok/install-poetry@v1
        with:
          version: latest
          virtualenvs-create: true
          virtualenvs-in-project: true

      - name: Install dependencies
        run: |
          set -e
          poetry install
          cd packages/engine && poetry install
          cd ../oracle && poetry install
          cd ../periscope && poetry install

      - name: Start services
        run: |
          docker run -d --name mockx-valkey -p 6379:6379 valkey/valkey:7-alpine --requirepass testpass
          sleep 5
          cd packages/engine
          poetry run uvicorn api.server:app --host 0.0.0.0 --port 8000 &
          sleep 10
          cd ../..

      - name: Run integration tests
        run: |
          cd packages/engine
          poetry run pytest tests/integration/ -v
          cd ../..

      - name: Cleanup
        if: always()
        run: |
          docker stop mockx-valkey || true
          docker rm mockx-valkey || true
